# Generated by Django 5.1.7 on 2025-03-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registered')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
